export const ENVIRONMENTS = {
  production_cn: "www.qianyierp.com",
  production_asia: "asia.qianyierp.com",
  test: "gerp-test1.800best.com",
} as const

export const STATE = { SUCCESS: "success", FAILURE: "failure" } as const

export const SYSTEM_ERRORS: Record<string, string> = {
  SYSTEM_ERROR: "系统异常，请联系官方对接人员",
  SIGNATURE_ERROR: "签名异常",
  APP_NOT_EXIST: "appId不存在",
  SERVICE_TYPE_NOT_EXIST: "接口不存在",
  APP_ID_CANNOT_BE_BLANK: "appId不能为空",
  SIGNATURE_CANNOT_BE_BLANK: "签名不能为空",
  SERVICE_TYPE_CANNOT_BE_BLANK: "请求接口不能为空",
  TIMESTAMP_CANNOT_BE_BLANK: "时间戳不能为空",
  SERVICE_TYPE_NOT_ALLOW: "接口未授权或不存在",
}

export const PLATFORM = {
  EBAY: "EBAY", AMAZON: "AMAZON", ALIEXPRESS: "ALIEXPRESS", WISH: "WISH",
  SHOPIFY: "SHOPIFY", WALMART: "WALMART", SHOPEE: "SHOPEE", LAZADA: "LAZADA",
  TIKTOK: "TIKTOK", TEMU: "TEMU", SHEIN: "SHEIN", OZON: "OZON",
  INDEPENDENT: "INDEPENDENT", DLZ_B2B: "DLZ_B2B",
} as const

export const SHOP_STATUS = { LOCK: "LOCK", UNLOCK: "UNLOCK" } as const

export const WAREHOUSE_KIND = { SHIP: "SHIP", TRANSFER: "TRANSFER", COMPLEX: "COMPLEX" } as const

export const SKU_TYPE = { SINGLE: "SINGLE", COMBINE: "COMBINE" } as const

export const ORDER_STATUS = {
  WAIT_PAYMENT: "WAIT_PAYMENT",
  WAIT_AUDIT: "WAIT_AUDIT",
  WAIT_SHIP: "WAIT_SHIP",
  SHIPPING: "SHIPPING",
  SHIP_FAILURE: "SHIP_FAILURE",
  PARTIALLY_SHIPPED: "PARTIALLY_SHIPPED",
  SHIPPED: "SHIPPED",
  CLOSED: "CLOSED",
} as const

export const RETURN_ORDER_STATUS = {
  NEW: "NEW", WAIT_AUDIT: "WAIT_AUDIT",
  WAIT_BUYER_RETURN: "WAIT_BUYER_RETURN", WAIT_BUYER_ACCEPT: "WAIT_BUYER_ACCEPT",
  WAIT_STORAGE: "WAIT_STORAGE", RECEIVING: "RECEIVING",
  FINISH: "FINISH", CLOSE: "CLOSE",
} as const

export const ASN_STATUS = {
  NEW: "NEW", DELETED: "DELETED", SHIPPING: "SHIPPING",
  RECEIVING: "RECEIVING", FINISHED: "FINISHED", CLOSED: "CLOSED",
} as const

export const ODO_STATUS = { WAIT_OUTBOUND: "WAIT_OUTBOUND", FINISHED: "FINISHED" } as const

export const ODO_TYPE = {
  MANUAL: "MANUAL", PURCHASE_RETURN: "PURCHASE_RETURN",
  FIRST_LEG: "FIRST_LEG", TRANSFER: "TRANSFER",
  LABEL_REPLACEMENT: "LABEL_REPLACEMENT", OTHER: "OTHER",
} as const

export const PURCHASE_STATUS = {
  NEW: "NEW", WAIT_CHECK: "WAIT_CHECK", WAIT_REVIEW: "WAIT_REVIEW",
  DENIED: "DENIED", APPROVED: "APPROVED", ORDERED: "ORDERED",
  RECEIVING: "RECEIVING", CLOSED: "CLOSED", FINISH: "FINISH",
} as const

export const PURCHASE_TYPE = { DIRECT: "DIRECT", TRANSFER: "TRANSFER" } as const

export const PAYMENT_METHOD = { COD: "COD", PAY_ONLINE: "PAY_ONLINE" } as const

export const RETURN_TYPE = { RETURN: "RETURN", SALES_RETURN: "SALES_RETURN", RESHIP: "RESHIP" } as const

export const ADJUSTMENT_SOURCE = { MANUAL: "MANUAL", AUTO: "AUTO" } as const

export const FIRST_LEG_STATUS = {
  NEW: "NEW", COMMITTED: "COMMITTED", SHIPPING: "SHIPPING",
  RECEIVING: "RECEIVING", FINISHED: "FINISHED", CLOSED: "CLOSED",
} as const

export const TRACKING_STATUS = {
  CREATED: "CREATED", IN_TRANSIT: "IN_TRANSIT",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY", DELIVERED: "DELIVERED",
  NOT_FOUND: "NOT_FOUND", UNDELIVERABLE: "UNDELIVERABLE",
} as const

export const CURRENCY = {
  PHP: "PHP", THB: "THB", VND: "VND", IDR: "IDR", MYR: "MYR",
  TWD: "TWD", SGD: "SGD", AUD: "AUD", JPY: "JPY", EUR: "EUR",
  GBP: "GBP", CAD: "CAD", USD: "USD", CNY: "CNY",
} as const

export const CUSTOM_FIELD_TABLE = {
  SYS_ITEM: "SYS_ITEM", SYS_ORDER: "SYS_ORDER",
  SYS_ODO: "SYS_ODO", SYS_ASN: "SYS_ASN",
} as const

export const CUSTOM_FIELD_TYPE = {
  NUMBER: "NUMBER", DATE: "DATE", STRING: "STRING", SELECT: "SELECT",
} as const
