export const ASN_WEBHOOK = "ASN_WEBHOOK"
export const SALES_ORDER_SHIPPING_WEBHOOK = "SALES_ORDER_SHIPPING_WEBHOOK"
export const RETURN_ORDER_WEBHOOK = "RETURN_ORDER_WEBHOOK"
export const TRACKING_WEBHOOK = "TRACKING_WEBHOOK"
